### ISSUE TITLE
Property React doesn't exist

### ISSUE THREAD

**Issue by afkcodes** [leegeunhyeok/react-native-esbuild#4]
Hi first of all hats off to your effort. this is an amazing work. I tried this with my project but it threw the following error:

```
error app ReferenceError: Property 'React' doesn't exist

This error is located at:
    in BottomTabs (created by App)
    in Unknown (created by App)
    in NVScene (created by Scene3)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by Scene3)
    in Scene3
    in Scene$1 (created by PopSync2)
    in PopSync2 (created by NavigationStack)
    in NVNavigationStack (created by NavigationStack)
    in NavigationStack (created by App)
    in NavigationHandler5 (created by App)
    in RCTView (at View.js:108)
    in View (created by Container2)
    in Container2 (created by EventProvider)
    in EventProvider (created by App)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App (at renderApplication.js:57)
    in RCTView (at View.js:108)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:108)
    in View (at AppContainer.js:133)
    in AppContainer2 (at renderApplication.js:50)
    in Tarana(RootComponent) (at renderApplication.js:67), js engine: hermes


```

Please have a look at it and please let me know if is there anything that i am doing wrong. I have followed the setup guide as well

**Comment by leegeunhyeok** [comment]
Hi, @afkcodes.

In development version(current alpha), jsx transform options weren't configured yet.

You can avoid this error with add React variable to your `.jsx`, `.tsx` files like this.

```jsx
// AS-IS
import { useState } from 'react';

// TO-BE
import React, { useState } from 'react';
```

If you want to check it before build, add [eslint rule](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md) to your project.

```js
// eslintrc.js
{
  files: ['*.jsx', '*.tsx'],
  rules: {
    'react/react-in-jsx-scope': 'error',
  },
}
```

However, a new jsx transform feature has been announced on React 17 and currently supported by Babel, Typescript, ..etc.

In additional, esbuild also supports for [jsx transform](https://esbuild.github.io/content-types/#auto-import-for-jsx) and I plan to support auto import for jsx soon.

**Comment by afkcodes** [comment]
Thank @leegeunhyeok  will surely add this and let you know.  You are amazing

**Comment by leegeunhyeok** [comment]
https://github.com/leegeunhyeok/react-native-esbuild/commit/c17e1c6bd0065fa443a07139ddaf8f167b16bf73

Release as `0.1.0-beta.13` soon.
