### ISSUE TITLE
[Question] 궁금한 점 질문 드립니다

### ISSUE THREAD

**Issue by jeongshin** [leegeunhyeok/react-native-esbuild#6]
안녕하세요. 라이브러리에 관심이 생겨서 몇가지 질문을 드리고 싶습니다. 

1. [react-native-esbuild](https://github.com/oblador/react-native-esbuild) 랑 혹시 어떤 차이점이 있나요?
2. Production 에서 쓸 수 있는 상황인가요?

**Comment by leegeunhyeok** [comment]
안녕하세요, @jeongshin 님.

1. 목적과 제공하는 주요 기능은 대체로 유사하다고 생각됩니다.
  1-1. 본 프로젝트는 JSC, Hermes 모두 지원하고 있으나, 링크로 남겨주신 프로젝트는 JSC 에서만 동작하는 것으로 확인됩니다.
  1-2. 본 프로젝트는 Babel 사용을 최소화 하기 위해 Sucrase, SWC 를 적극 활용하고 있으나, 링크로 남겨주신 프로젝트는 Babel 만을 사용하는 것으로 확인됩니다. 성능 차이가 있을 수 있습니다.
  1-3. 본 프로젝트는 독립적인 cli 를 제공하고 있으나, 링크로 남겨주신 프로젝트는 react-native 구성에 종속되는 형태로 동작합니다.
2. 현재는 "아니오" 입니다.
  2-1. 실제 프로덕션 환경에 적용하기 위해 노력 중에 있으나, Hermes 환경에서의 성능 이슈가 발견되어 확인 중에 있습니다 (#5)
  2-2. 그 외 JSC, V8 환경에서는 완벽하게 동작하고, 실제 빌드 프로세스의 경우에도 스크립트만 조금 수정하면 기존 CI/CD 에서 동작하기 때문에, 위 이슈만 해결된다면 긍정적으로 바라볼 수 있을 것 같습니다.

단, 특정 라이브러리에서의 빌드 이슈, New Architecture 구성에서의 이슈 등이 발생할 수 있고 아직 테스트 되지 않은 부분이 많기 때문에, 보수적인 접근이 필요합니다.

**Comment by jeongshin** [comment]
@leegeunhyeok 답변 감사합니다 🙇🏻‍♂️
